root: true
env:
  browser: true
  es6: true
  node: true
  commonjs: true
  jest: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
    semi: 
      - error
      - "always"
    quotes:
      - error
      - "single"
    no-trailing-spaces:
      - error
    eqeqeq:
      - error
      - "always"
    react/prop-types:
      - 0
    react/react-in-jsx-scope:
      - 0
    no-console:
      - error
    array-callback-return:
      - 2
      - allowImplicit: true
        checkForEach: false
    arrow-body-style:
      - error
      - as-needed
    block-scoped-var:
      - error
    

